### ISSUE TITLE
Doors cant be lock

### ISSUE THREAD

**Issue by ClockProgramming** [EvolSoft/DoorLocker#2]
Doors cant get locked

**Comment by Flavius12** [comment]
This plugin **is not complete** and **it's not supported or made by me**. For any question ask @TheDiamondYT1.

**Comment by ClockProgramming** [comment]
kk

**Comment by TheDiamondYT1** [comment]
I will try and fix afterwards. Do you get any console errors when trying to lock the door?

(I haven't been able to test due to not having PC access today. I could only check if it loads)

**Comment by ClockProgramming** [comment]
no
